### ISSUE TITLE
Cant able to read the whole data from GATT server that is below 20 bytes

### ISSUE THREAD

**Issue by Padmavathi-Balachandran** [massi-ang/amazon-freertos-ble-provisioning-demo#5]
Hi, I am new to ble gatt concept.I am using amazon freertos and esp32. I tried the ble demo in the amazon freertos. 

void vRead( IotBleAttributeEvent_t * pEventParam )
{
    IotBleReadEventParams_t * pxReadParam;
    IotBleAttributeData_t xAttrData = { 0 };
    IotBleEventResponse_t xResp;
   
    xResp.pAttrData = &xAttrData;
    xResp.rspErrorStatus = eBTRspErrorNone;
    xResp.eventStatus = eBTStatusFail;
    xResp.attrDataOffset = 0;
    if( pEventParam->xEventType == eBLERead )
    {
        pxReadParam = pEventParam->pParamRead;
        xResp.pAttrData->handle = pxReadParam->attrHandle;
        xResp.pAttrData->pData = thing_name;
        xResp.pAttrData->size = sizeof( thing_name );
        xResp.attrDataOffset = 0;
        xResp.eventStatus = eBTStatusSuccess;
        IotBle_SendResponse( &xResp, pxReadParam->connId, pxReadParam->transId );
    }
} 

I am trying to read the thing_name from GATT server.My thing name is ESP_FCF7C219B598.But i am able to get only the first  
 four letters in the mobile client. Whatever data i try to read, the same thing happens.
![Screenshot_20200918_014950](https://user-images.githubusercontent.com/71666510/93812174-de09ae80-fc6e-11ea-914f-a92f9a542933.jpg)

This is the value i am getting--> "ESP_".  I think it is the issue with the size. I have the configurations in gatt_api.h as
#define GATT_MAX_ATTR_LEN                       600   
/* default GATT MTU size over LE link
*/
#define GATT_DEF_BLE_MTU_SIZE               23

I am not sure where i need to make the changes to get the full data

Can somebody please help me to get the full data on the mobile client?

**Comment by massi-ang** [comment]
You can change the size of the advertised name by adding this `#define` to the `vendors/espressif/boards/esp32/aws_demos/config_files/iot_ble_config.h` file

```
#define IOT_BLE_DEVICE_SHORT_LOCAL_NAME_SIZE    4
``` 

replace 4 with the desired number.

As explained [here](https://devzone.nordicsemi.com/f/nordic-q-a/20602/max-length-of-the-device-name-in-nrf52832) you can only get the first 29 bytes of the name in an Advertising packet.

**Comment by Padmavathi-Balachandran** [comment]
Thank you so much sir for your help. The problem solved by changing the sizeof() to strlen() function here--> 
xResp.pAttrData->size = sizeof( thing_name );

The information you provided helped me to know more about the configurations. Thank you!!

**Comment by massi-ang** [comment]
Where is that line of code?

**Comment by Padmavathi-Balachandran** [comment]
It is here--->

void vRead( IotBleAttributeEvent_t * pEventParam )
{
IotBleReadEventParams_t * pxReadParam;
IotBleAttributeData_t xAttrData = { 0 };
IotBleEventResponse_t xResp;

xResp.pAttrData = &xAttrData;
xResp.rspErrorStatus = eBTRspErrorNone;
xResp.eventStatus = eBTStatusFail;
xResp.attrDataOffset = 0;
if( pEventParam->xEventType == eBLERead )
{
    pxReadParam = pEventParam->pParamRead;
    xResp.pAttrData->handle = pxReadParam->attrHandle;
    xResp.pAttrData->pData = thing_name;
    **xResp.pAttrData->size = sizeof( thing_name )**;
    xResp.attrDataOffset = 0;
    xResp.eventStatus = eBTStatusSuccess;
    IotBle_SendResponse( &xResp, pxReadParam->connId, pxReadParam->transId );
}
}
